#!/bin/bash
source FuhaoLab.conf
TargetFile=/usr/share/gedit/plugins/snippets/sh.xml
#TargetFile=${HOME}/.config/gedit/snippets/sh.xml
Endingline="</snippets>"
TestEmptyFile=0
TestSudo=""
UseSudo=0


if [[ "$TargetFile" =~ \/usr\/ ]]; then
	PrintInfo "Info: need sudo to run following CMDs"
	TestSudo="sudo "
	UseSudo=1
else
	PrintInfo "Info: No need sudo"
	UseSudo=0
fi



if [ ! -s $TargetFile ]; then
	TestEmptyFile=1

	$TestSudo bash -c "cat>>$TargetFile<<END111
<?xml version="1.0" encoding="UTF-8"?>
<snippets language="sh">
END111
"
fi

$TestSudo bash -c "sed -i '/<\/snippets>/d' $TargetFile"

$TestSudo bash -c "echo '  <snippet id=\"wrapper\">
    <text><![CDATA[#!/bin/bash

export PATH=\$1/bin:\\\$PATH
export LIBRARY_PATH=\$1/lib:\\\$LIBRARY_PATH
export LD_LIBRARY_PATH=\$1/lib:\\\$LD_LIBRARY_PATH
export INCLUDE_PATH=\$1/include:\\\$INCLUDE_PATH
export CPLUS_INCLUDE_PATH=\$1/include:\\\$CPLUS_INCLUDE_PATH
export PKG_CONFIG_PATH=\$1/lib/pkgconfig:\\\$PKG_CONFIG_PATH
export MAN_PATH=\$1/share/man:\\\$MAN_PATH
export ACLOCAL_PATH=\$1/share/aclocal:\\\$ACLOCAL_PATH]]></text>
    <description>wrapper</description>
    <tag>wrapper</tag>
  </snippet>' >> $TargetFile" 

if [ $TestEmptyFile -eq 0 ]; then
#	echo "$LastLine" >> $TargetFile
	$TestSudo bash -c "echo \"$Endingline\" >> $TargetFile"

else
	$TestSudo bash -c "echo \"$Endingline\" >> $TargetFile"
fi

exit 0
