#!/bin/bash
source FuhaoLab.conf
TargetFile=/usr/share/gedit/plugins/snippets/perl.xml
#TargetFile=${HOME}/.config/gedit/snippets/perl.xml
Endingline="</snippets>"
TestEmptyFile=0
TestSudo=""
UseSudo=0


if [[ "$TargetFile" =~ \/usr\/ ]]; then
	PrintInfo "Info: need sudo to run following CMDs"
	TestSudo="sudo "
	UseSudo=1
else
	PrintInfo "Info: N need sudo"
	UseSudo=0
fi



if [ ! -s $TargetFile ]; then
	TestEmptyFile=1

	$TestSudo bash -c "echo \"
<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<snippets language=\"Perl\" >>$TargetFile"
fi

$TestSudo bash -c "sed -i '/<\/snippets>/d' $TargetFile"

$TestSudo bash -c "echo '  <snippet id=\"simhelp\">
    <text><![CDATA[#!/usr/bin/env perl
use strict;
use warnings;
use constant USAGE =><<EOH;

usage: \\\$0 \$1

Version: 20\$2

Descriptions
\$3

EOH
die USAGE if (scalar(@ARGV) != 3);


]]></text>
    <description>simhelp</description>
    <tag>simhelp</tag>
  </snippet>' >> $TargetFile"

if [ $TestEmptyFile -eq 0 ]; then
#	echo "$LastLine" >> $TargetFile
	$TestSudo bash -c "echo \"$Endingline\" >> $TargetFile"

else
	$TestSudo bash -c "echo \"$Endingline\" >> $TargetFile"
fi

exit 0
